sentence = input("Enter a sentence: ")
print(f"Your sentence in uppercase: {sentence.upper()}")
print(f"Your sentence in lowercase: {sentence.lower()}")
print(f"The total number of characters is: {len(sentence)}")
print(f"The total number of words is: {len(sentence.split())}")
print(f"The first character of the sentence is: {sentence[0]}")
print(f"The last character of the sentence is: {sentence[-1]}")
print(f"The sentence in reverse: {sentence[::-1]}")
print(f"The number of repetition of the letter a is: {sentence.count("a")}")
